# Site settings
title: My Portfolio
email: webdeveloperchintan@gmail.com
url: https://webdevchintan.github.io
description: "Hello and Welcome to my profile! Looking for a freelancer to work on your next project? Or just need someone to fix issues/bugs ASAP? Look no further, because I’m here for you! I’m Chintan Patel. I've 7 years experience in developing web and mobile applications, web services, using React Native,React Js and other Cross platform as well as PHP and Node Js technologies.I've successfully completed Website development projects, App Development, API integration projects, Payment gateway integration projects, Web API project. Whether its a responsive website you need or you need Reliable Mobile application along with the web services for your mobile application or you want to integrate third party API, I'm here to provide customised solution for all your website/App development needs. I'm interested in any projects in React native technology.  I don't sell you my programming skills, I achieve your business goals. I'm passionate about providing a fully customised solution to my clients with smile on their face:) "
keywords: "React Native,React Js,WordPress, MVC, JavaScript,Jquery, SQL Server, PHP,Node Js, Mobile Application Developer, Hybrid App Developer"
skills: "Web and Mobile Application Developer"
meta_author: Patel Chintan

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 18bc9c #80B3FF
  primary-rgb: "24,288,156" #"128,179,255"
  secondary: 2c3e50 #FD6E8A
  secondary-dark: 233140 #A2122F

# Footer settings
footer:
  copyright: Chintan Patel
  location: Location
  social: Around the Web
  credits: Credits

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/chintanp15
  - title: facebook
    url:
  - title: github
    url: http://github.com/webdevchintan

# Postal address (add as many lines as necessary)
address:
  - line: Gujarat
  - line: India

# Build settings
markdown: kramdown
permalink: pretty

#for posts
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      permalink: ""
